=== mobileben/eos-game-engine/tools/EOSRsrcBundler/eosrsrcbundle.dtd
<!ELEMENT bundle (name, texdb?, texatlasdb?, sprtexatlasmappingdb?, spritedb?, spranimdb?)>
<!ELEMENT texdb (name, tex+)>
<!ELEMENT tex (name, filename, width, height, colorformat, minmipmapfilter?, magmipmapfilter?, wraps?, wrapst?, texenvmode?)>
<!ELEMENT texatlasdb (name, texatlas+)>
<!ELEMENT texatlas (name, filename, texname?)>
<!ELEMENT sprtexatlasmappingdb (name, sprtexatlasmapping+)>
<!ELEMENT sprtexatlasmapping (name, filename)>
<!ELEMENT spritedb (name, sprite+)>
<!ELEMENT sprite (name, filename, texatlasnamelist?, mappingname?)>
<!ELEMENT spranimdb (name, spranim+)>
<!ELEMENT spranim (name, filename, spritename?)>
<!ELEMENT texatlasnamelist (name+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT texname (#PCDATA)>
<!ELEMENT spritename (#PCDATA)>
<!ELEMENT mappingname (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT colorformat (#PCDATA)>
<!ELEMENT minmipmapfilter (#PCDATA)>
<!ELEMENT magmipmapfilter (#PCDATA)>
<!ELEMENT wraps (#PCDATA)>
<!ELEMENT wrapt (#PCDATA)>
<!ELEMENT texenvmode (#PCDATA)>

=== mobileben/eos-game-engine/tools/EOSRsrcBundler/eosrsrcbundle.xml
<?xml version="1.0" encoding="ISO-8859-1"?> 
<!DOCTYPE bundle SYSTEM "eosrsrcbundle.dtd">
<bundle>
    <name>EOSRSRCBUNDLE</name>
    <texdb>
        <name>TEXTUREDB</name>
        <tex>
            <name>publisher</name>
            <filename>publisher.gl</filename>
            <width>256</width>
            <height>128</height>
            <colorformat>TextureFormatGL_P8_RGBA_8888</colorformat>
        </tex>
    </texdb>
    <texatlasdb>
        <name>TEXATLASDB</name>
        <texatlas>
            <name>publisher</name>
            <filename>publisher.bin</filename>
            <texname>publisher</texname>
        </texatlas>
    </texatlasdb>
    <spritedb>
        <name>SPRITEDB</name> 
        <sprite>
            <name>publisher</name>
            <filename>publisher_sprite.bin</filename>
            <texatlasnamelist>
                <name>publisher</name>
            </texatlasnamelist>
        </sprite>
    </spritedb>
    <spranimdb>
        <name>SPRITEANIMDB</name> 
        <spranim>
            <name>publisher</name>
            <filename>publisher_anim.bin</filename>
            <spritename>publisher</spritename>
        </spranim>
    </spranimdb>
</bundle>
